#!/usr/bin/env bash
# Generate deploy/k3s/secret.yaml with fresh values.
#
#   ./make-secret.sh > secret.yaml
#   kubectl apply -f secret.yaml
#
# Pass --admin USER PASSWORD to also seed the first operator account.
set -euo pipefail

ADMIN_USER=""
ADMIN_PASSWORD=""
while [ $# -gt 0 ]; do
  case "$1" in
    --admin) ADMIN_USER="${2:-}"; ADMIN_PASSWORD="${3:-}"; shift 2 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
  shift
done

if [ -n "$ADMIN_USER" ] && [ "${#ADMIN_PASSWORD}" -lt 12 ]; then
  echo "the admin password must be at least 12 characters" >&2
  exit 1
fi

# openssl is not on every minimal image; /dev/urandom is.
rand_hex() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$1"
  else
    head -c "$(( $1 * 2 ))" /dev/urandom | od -An -tx1 | tr -d ' \n' | cut -c "1-$(( $1 * 2 ))"
  fi
}
rand_key() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 32 | tr '+/' '-_' | tr -d '='
  else
    rand_hex 32
  fi
}

cat <<YAML
# Generated by make-secret.sh. Do not commit.
apiVersion: v1
kind: Secret
metadata:
  name: syphax-secrets
  namespace: syphax
type: Opaque
stringData:
  POSTGRES_DB: syphax
  POSTGRES_USER: syphax
  POSTGRES_PASSWORD: "$(rand_hex 24)"
  SYPHAX_SECRET_KEY: "$(rand_key)"
  SYPHAX_API_KEY: ""
  SYPHAX_ADMIN_USER: "${ADMIN_USER}"
  SYPHAX_ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
  WPSCAN_API_TOKEN: ""
  GITHUB_TOKEN: ""
YAML
